### ISSUE TITLE
Is there a plan to support multipart upload for large files?

### ISSUE THREAD

**Issue by zhangkaizhao** [NoXF/oss-rust-sdk#14]
Hello! Nice crate! I have some questions.

* Is this an official sdk?
* Is there a plan to support multipart upload for large files?

Thanks!

**Comment by NoXF** [comment]
1. No, but it is inspired by https://github.com/aliyun/aliyun-oss-cpp-sdk
3. No plans at this moment, PR is very welcome

**Comment by zhangkaizhao** [comment]
Got it. Thanks for the reply!
