### ISSUE TITLE
thread 'actix-rt|system:0|arbiter:0' panicked at 'Cannot drop a runtime in a context where blocking is not allowed. This happens when a runtime is dropped from within an asynchronous context.'

### ISSUE THREAD

**Issue by Lisheri** [NoXF/oss-rust-sdk#24]
this code may cause panic:

```rust
pub async fn get_all_list(
    app_state: web::Data<AppState>,
    params: web::Query<ListQuery>,
) -> Result<HttpResponse, MyError> {
    let headers: HashMap<String, String> = HashMap::new();
    let mut resources: HashMap<String, Option<String>> = HashMap::new();
    let inner_params = params.into_inner();
    resources.insert("prefix".into(), Some(inner_params.prefix));
    resources.insert("max_keys".into(), Some(inner_params.max_keys));

    app_state
        .oss_client
        .get_list(headers, resources)
        .map(|list| {
            println!("list is: {:?}", &list);
            HttpResponse::Ok().json(ResponseResult::<ListObjects> {
                code: 0,
                msg: "success",
                data: list,
            })
        })
}

impl OssClient {
    pub fn new() -> Self {
        Self {
            instance: OSS::new(
                Into::<Cow<str>>::into(ACCESS_KEY_ID),
                Into::<Cow<str>>::into(ACCESS_KEY_SECRET),
                Into::<Cow<str>>::into(REGION),
                Into::<Cow<str>>::into(BUCKET),
            ),
        }
    }
    pub fn get_list(
        &self,
        headers: HashMap<String, String>,
        resources: HashMap<String, Option<String>>,
    ) -> Result<ListObjects, MyError> {
        let list = self.instance.list_object(headers, resources);
        // println!("run at here: {:?}", list);
        match list {
            Ok(res) => Ok(res),
            Err(err) => {
                println!("err msg is: {:?}", err);
                Err(MyError::ActixError(err.to_string()))
            }
        }
    }
}
```

I would't have this problem if I used a sync fn, but I need async api to listen to front-end requests.

**Comment by Lisheri** [comment]
the easiest way to reproduce this problem is this code:

```rust
#[actic_rt::main]
async fn main() {
  let headers: HashMap<String, String> = HashMap::new();
  let mut resources: HashMap<String, Option<String>> = HashMap::new();
   resources.insert("prefix".into(), Some("images".to_string()));
   resources.insert("max_keys".into(), Some("10".into()));

    let _ = OSS::new().get_list(headers, resources).map(|list| {
            println!("list is: {:?}", &list);
      });
}
```

Although I don't need async fn at here~, but it can reproduce above problem

**Comment by Lisheri** [comment]
is this problem caused by "actix_rt"?

**Comment by Lisheri** [comment]
<img width="1012" alt="image" src="https://github.com/NoXF/oss-rust-sdk/assets/49238808/d6e40d98-6c3f-4af9-a01f-356d11c0e829">

**Comment by Lisheri** [comment]
I avoid this problem by thread::spawn, but I don't know if this is the normal way.

**Comment by NoXF** [comment]
```rust
#[actix_rt::main]
async fn main() {
    use oss_rust_sdk::async_object::*;

    let oss_instance = OSS::new(
        "****",
        "****",
        "****",
        "****",
    );
    let mut params = HashMap::new();
    params.insert("max-keys", Some("5"));

    let result = oss_instance.list_object(None, params).await.unwrap();

    for object in result.contents() {
        dbg!(&object.key(), &object.id());
    }
}
```
I have tested the above code, it's working correctly. Since I am not very familiar with Actix, you may need more check about if used the wrong API or other problems

**Comment by Lisheri** [comment]
> ```rust
> #[actix_rt::main]
> async fn main() {
>     use oss_rust_sdk::async_object::*;
> 
>     let oss_instance = OSS::new(
>         "****",
>         "****",
>         "****",
>         "****",
>     );
>     let mut params = HashMap::new();
>     params.insert("max-keys", Some("5"));
> 
>     let result = oss_instance.list_object(None, params).await.unwrap();
> 
>     for object in result.contents() {
>         dbg!(&object.key(), &object.id());
>     }
> }
> ```
> 
> I have tested the above code, it's working correctly. Since I am not very familiar with Actix, you may need more check about if used the wrong API or other problems

ok, I have avoided it by child thread, it might be caused by actix_rt and tokio.
I found some sayings about this yesterday.

**Comment by Lisheri** [comment]
Hello, I look for forders through "prefix" and "delimiter", but all "CommonPrefixs" are truncated after "quick_xml::de::from_str::<ListObjects>(&body)?;" processed
But it exists in body.
![image](https://github.com/NoXF/oss-rust-sdk/assets/49238808/4c09f428-93f2-4f1f-9b8b-b53f8c328d66)
![image](https://github.com/NoXF/oss-rust-sdk/assets/49238808/cd49b08d-bd8e-4f95-9f09-c751fafdeb62)

**Comment by Lisheri** [comment]
> Hello, I look for forders through "prefix" and "delimiter", but all "CommonPrefixs" are truncated after "quick_xml:🇩🇪:from_str::(&body)?;" processed But it exists in body. ![image](https://user-images.githubusercontent.com/49238808/257787796-4c09f428-93f2-4f1f-9b8b-b53f8c328d66.png) ![image](https://user-images.githubusercontent.com/49238808/257787832-cd49b08d-bd8e-4f95-9f09-c751fafdeb62.png)

![image](https://github.com/NoXF/oss-rust-sdk/assets/49238808/04b763df-5ead-4f55-ad87-9d66845670d5)

**Comment by Lisheri** [comment]
![image](https://github.com/NoXF/oss-rust-sdk/assets/49238808/141333e6-d7d5-4a28-8c70-b58514a5c93f)
Is this possible to add "CommonPrefixes" here?

**Comment by NoXF** [comment]
> 
sure, try 0.9.2 to use "CommonPrefixes", and thx for your commit.

**Comment by Lisheri** [comment]
> 

ok, it's ready to run
