### ISSUE TITLE
cannot infer type for `S3`

### ISSUE THREAD

**Issue by TURIING** [NoXF/oss-rust-sdk#6]
使用put_object_from_file（）函数的时候报了个

error[E0282]: type annotations needed
 --> src/main.rs:6:31
  |
6 |     let result = oss_instance.put_object_from_file(filename, "tmp.pdf", None, None);
  |                               ^^^^^^^^^^^^^^^^^^^^ cannot infer type for `S3`

error: aborting due to previous error

**Comment by NoXF** [comment]
为了让 filename、object 与 headers，resources 的类型不同，所以 headers、resources 都是 None 的时候没法推断默认 S3 的类型，可以先这样告诉编译器类型。
`let result = oss_instance.put_object_from_file(filename, "tmp.pdf", None::<HashMap<&str, &str>>, None);`
